In [5]:
#Name: Neeraja Prabhudesai
# Enrollment no - 0006

In [4]:
# training the neural network on this simple data to understand the concept of RNN as it is a sequential data
# previous char i/p next char o/p - kinda thing in RNN 
alphabets = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [6]:
# enumerate - assigns the sequence no to perticular element in the string
list(enumerate(alphabets))

[(0, 'A'),
 (1, 'B'),
 (2, 'C'),
 (3, 'D'),
 (4, 'E'),
 (5, 'F'),
 (6, 'G'),
 (7, 'H'),
 (8, 'I'),
 (9, 'J'),
 (10, 'K'),
 (11, 'L'),
 (12, 'M'),
 (13, 'N'),
 (14, 'O'),
 (15, 'P'),
 (16, 'Q'),
 (17, 'R'),
 (18, 'S'),
 (19, 'T'),
 (20, 'U'),
 (21, 'V'),
 (22, 'W'),
 (23, 'X'),
 (24, 'Y'),
 (25, 'Z')]

In [7]:
# preparing input and output data using this list
'''2 datasets required - 1.encode string into numerical form 2.to decode the result into string againat the time of prediction - for this
purpuse dictionary comprehension method is used''';

In [8]:
for i, c in enumerate(alphabets):
    print(i, c)

0 A
1 B
2 C
3 D
4 E
5 F
6 G
7 H
8 I
9 J
10 K
11 L
12 M
13 N
14 O
15 P
16 Q
17 R
18 S
19 T
20 U
21 V
22 W
23 X
24 Y
25 Z


In [9]:
# for encoding
int_to_char = dict((i,c) for i, c in enumerate(alphabets))

In [10]:
int_to_char

{0: 'A',
 1: 'B',
 2: 'C',
 3: 'D',
 4: 'E',
 5: 'F',
 6: 'G',
 7: 'H',
 8: 'I',
 9: 'J',
 10: 'K',
 11: 'L',
 12: 'M',
 13: 'N',
 14: 'O',
 15: 'P',
 16: 'Q',
 17: 'R',
 18: 'S',
 19: 'T',
 20: 'U',
 21: 'V',
 22: 'W',
 23: 'X',
 24: 'Y',
 25: 'Z'}

In [11]:
# for decoding
char_to_int = dict((c, i) for i, c in enumerate(alphabets))

In [12]:
char_to_int

{'A': 0,
 'B': 1,
 'C': 2,
 'D': 3,
 'E': 4,
 'F': 5,
 'G': 6,
 'H': 7,
 'I': 8,
 'J': 9,
 'K': 10,
 'L': 11,
 'M': 12,
 'N': 13,
 'O': 14,
 'P': 15,
 'Q': 16,
 'R': 17,
 'S': 18,
 'T': 19,
 'U': 20,
 'V': 21,
 'W': 22,
 'X': 23,
 'Y': 24,
 'Z': 25}

In [14]:
#creating sequential i/p o/p - e.g. 1st char is i/p 2nd char will be o/p
# Z will not be i/p and A will not be o/p anywhere
seq_length = 1
x = []
y = []

for i in range (len(alphabets)-1):
    seq_in = alphabets[i:i+seq_length]
    seq_out = alphabets[i+seq_length]
    print(seq_in, '->' , seq_out)
    x.append([char_to_int[char] for char in seq_in]) # appended to the list as we want it in the list format
    y.append(char_to_int[seq_out])

A -> B
B -> C
C -> D
D -> E
E -> F
F -> G
G -> H
H -> I
I -> J
J -> K
K -> L
L -> M
M -> N
N -> O
O -> P
P -> Q
Q -> R
R -> S
S -> T
T -> U
U -> V
V -> W
W -> X
X -> Y
Y -> Z


In [15]:
x

[[0],
 [1],
 [2],
 [3],
 [4],
 [5],
 [6],
 [7],
 [8],
 [9],
 [10],
 [11],
 [12],
 [13],
 [14],
 [15],
 [16],
 [17],
 [18],
 [19],
 [20],
 [21],
 [22],
 [23],
 [24]]

In [16]:
y

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25]

In [18]:
import numpy as np

In [19]:
# necessary step in neural network
X = np.reshape(x, (len(x), seq_length, 1))
# 1 - how many number of characters are present in single sequence
# x- that we want to reshape
# len - sequence length

In [21]:
X.shape

(25, 1, 1)

In [22]:
X

array([[[ 0]],

       [[ 1]],

       [[ 2]],

       [[ 3]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[ 8]],

       [[ 9]],

       [[10]],

       [[11]],

       [[12]],

       [[13]],

       [[14]],

       [[15]],

       [[16]],

       [[17]],

       [[18]],

       [[19]],

       [[20]],

       [[21]],

       [[22]],

       [[23]],

       [[24]]])

In [23]:
# scaling - shifting the data in the range of 0 to 1 without changing the internal relation
a = np.array([7,3,0,2,4,8,5])

In [24]:
# dividing by highest no in the list
# this step is to speed up th process of ML
# here only magnitudes are changed
a / 8

array([0.875, 0.375, 0.   , 0.25 , 0.5  , 1.   , 0.625])

In [28]:
#preperation of input data

In [25]:
X = X / 25

In [26]:
X

array([[[0.  ]],

       [[0.04]],

       [[0.08]],

       [[0.12]],

       [[0.16]],

       [[0.2 ]],

       [[0.24]],

       [[0.28]],

       [[0.32]],

       [[0.36]],

       [[0.4 ]],

       [[0.44]],

       [[0.48]],

       [[0.52]],

       [[0.56]],

       [[0.6 ]],

       [[0.64]],

       [[0.68]],

       [[0.72]],

       [[0.76]],

       [[0.8 ]],

       [[0.84]],

       [[0.88]],

       [[0.92]],

       [[0.96]]])

In [27]:
# preperation of output data
# one-hot encoding- 

In [29]:
a = np.array([3,0,2,3,3,1,2,3,1,0,2,0,0,0,1,2,3])

In [30]:
a

array([3, 0, 2, 3, 3, 1, 2, 3, 1, 0, 2, 0, 0, 0, 1, 2, 3])

In [31]:
from keras.utils import to_categorical

In [32]:
#requirement of multiclass classification
to_categorical(a)

array([[0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
# one-hot encoding for o/p data
y = to_categorical(y)

In [34]:
y

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 

In [35]:
y.shape
#25 rows 

(25, 26)

In [36]:
X.shape

(25, 1, 1)

In [37]:
#input
X[0]

array([[0.]])

In [38]:
#output 
y[0]

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
## build the model

In [40]:
from keras.models import Sequential
from keras.layers import Dense, LSTM

In [41]:
#Create the object of RNN
model = Sequential()

#add the LSTM layer
layer1 = LSTM(32, input_shape = (X.shape[1], X.shape[2])) #first parameter - how many bytes are required i.e. memory, 2nd para - i/p shape - 1 x 1
model.add(layer1)

#add the o/p layer
layer2 = Dense(26, activation='softmax')
model.add(layer2)


C:\Users\unmes\anaconda3\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [42]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                          │ (None, 32)                  │           4,352 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 26)                  │             858 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 5,210 (20.35 KB)

 Trainable params: 5,210 (20.35 KB)

 Non-trainable params: 0 (0.00 B)

In [43]:
from keras.utils import plot_model

In [44]:
plot_model(model, show_layer_activations=True, show_layer_names=True, show_shapes=True)

AttributeError: module 'pydot' has no attribute 'InvocationException'

In [45]:
#Compile the model

In [46]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [47]:
## train the model

In [48]:
model.fit(X, y, epochs=1000, batch_size=1)

Epoch 1/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.0000e+00 - loss: 3.2625
Epoch 2/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0906 - loss: 3.2540   
Epoch 3/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1493 - loss: 3.2532   
Epoch 4/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0936 - loss: 3.2538   
Epoch 5/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0801 - loss: 3.2478   
Epoch 6/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0119 - loss: 3.2519   
Epoch 7/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0290 - loss: 3.2486   
Epoch 8/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1098 - loss: 3.2390   
Epoch 9/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0260 - loss: 3.2420   
Epoch 10/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 3.2339
Epoch 11/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0605 - loss: 3.2288   
Epoch 12/1000
25/

In [49]:
model.evaluate(X, y, batch_size=1)

25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9953 - loss: 1.1235   


[1.3685624599456787, 0.9599999785423279]

In [50]:
#predictions

In [56]:
new = 'E'
new = char_to_int[new]
new = np.reshape(new, (1,1,1))
new = new / 25
# input data is prepared
result = model.predict(new, verbose=False)
result = np.argmax(result)
int_to_char[result]

'F'

In [57]:
result1 = model.predict(new, verbose=False)
result1

array([[4.6201912e-10, 2.5688390e-05, 6.8206680e-03, 7.4516259e-02,
        2.4602997e-01, 3.0785117e-01, 2.2197470e-01, 9.8077089e-02,
        3.3449654e-02, 8.8815112e-03, 1.8490200e-03, 4.2733905e-04,
        8.0965066e-05, 1.3644303e-05, 2.0644004e-06, 1.9916342e-07,
        3.8411780e-08, 4.2099209e-09, 5.0025689e-10, 5.0739166e-11,
        6.7999387e-12, 7.5592999e-13, 5.0943712e-14, 2.7010403e-15,
        1.5748170e-16, 7.3545116e-18]], dtype=float32)